FROM ubuntu:latest as builder

RUN apt-get update
RUN apt-get install curl -y
RUN curl -L -o /tmp/go.sh https://install.direct/go.sh
RUN chmod +x /tmp/go.sh
RUN /tmp/go.sh

FROM shadowsocks/shadowsocks-libev:latest

RUN uname -a

# ss-4

COPY s.json /etc/shadowsocks-libev/config.json

# pv-2

COPY --from=builder /usr/bin/v2ray/v2ray /usr/bin/v2ray/
COPY --from=builder /usr/bin/v2ray/v2ctl /usr/bin/v2ray/
COPY --from=builder /usr/bin/v2ray/geoip.dat /usr/bin/v2ray/
COPY --from=builder /usr/bin/v2ray/geosite.dat /usr/bin/v2ray/
COPY v.json /etc/v2ray/config.json

USER root
RUN set -ex && \
    apk update && apk --no-cache add ca-certificates && \
    mkdir /var/log/v2ray/ &&\
    chmod +x /usr/bin/v2ray/v2ctl && \
    chmod +x /usr/bin/v2ray/v2ray
    
# sshd-0

RUN apk update && apk add --no-cache openssh echo sed \
		       && mkdir -p /root/.ssh \
               && mkdir /var/run/sshd \
               && echo 'root:admin' |chpasswd \
               && sed -ri 's/^#?PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config \
               && sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config \
               && sed -ri 's/^#?Port .*/Port 16100/' /etc/ssh/sshd_config

# Complete

COPY run.sh /root/run.sh
RUN chmod +x /root/run.sh

RUN apk add --no-cache bash

RUN rm -rf /var/cache/apk/* /tmp/* 

EXPOSE 16100
EXPOSE 16102
EXPOSE 16103
EXPOSE 16104

CMD ["/bin/bash", "/root/run.sh"]
